// NAMI St. Louis — Partner directory (static data)
// Organizations in the St. Louis region that serve people navigating
// mental illness, their families, and supporters. Filterable by
// service type, population served, language, Medicaid, and sliding
// scale.
//
// IMPORTANT: This is a prototype dataset. Phone numbers, URLs,
// accepted insurance, and population focus should be verified with
// each organization before the directory is published. The UI
// surfaces this caveat prominently.

const PARTNERS_DATA = [
  {
    id: "bhr",
    name: "Behavioral Health Response (BHR)",
    short: "24/7 mobile crisis for the St. Louis metro.",
    description: "Free 24/7 crisis line answered by trained clinicians. Mobile crisis teams dispatch to homes, schools, and community locations across St. Louis City and the surrounding counties — a less police-involved alternative for acute mental-health crises.",
    phone: "314-469-6644",
    website: "https://www.bhrstl.org/",
    services: ["crisis", "mobile-crisis"],
    languages: ["english", "spanish"],
    populations: ["general"],
    medicaid: true,
    slidingScale: true,
    hours: "24/7",
    region: "St. Louis metro",
    urgent: true,
  },
  {
    id: "988",
    name: "988 Suicide & Crisis Lifeline",
    short: "Free, confidential, 24/7 — for anyone in emotional distress.",
    description: "National call, text, and chat lifeline routed to local crisis centers. For you, someone you love, or any situation where a human at the other end would help. Spanish line available.",
    phone: "988",
    website: "https://988lifeline.org/",
    services: ["crisis"],
    languages: ["english", "spanish"],
    populations: ["general", "veterans", "lgbtq", "youth"],
    medicaid: null,
    slidingScale: true,
    hours: "24/7",
    region: "National",
    urgent: true,
  },
  {
    id: "namistl",
    name: "NAMI St. Louis",
    short: "Family support groups, education, advocacy.",
    description: "Free education programs (Peer-to-Peer, Family-to-Family), support groups for individuals and families, and local advocacy. The NAMI HelpLine (1-800-950-6264) is open Mon-Fri 9am-9pm CT for supporters too.",
    phone: "314-962-4670",
    website: "https://namistl.org/",
    services: ["family-support", "education", "peer-support"],
    languages: ["english"],
    populations: ["family", "general"],
    medicaid: null,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis metro",
  },
  {
    id: "namimo",
    name: "NAMI Missouri",
    short: "Statewide affiliate — policy, education, family support.",
    description: "State affiliate of the National Alliance on Mental Illness. Policy advocacy, Smarts Advocacy training, and connection to local NAMI affiliates across Missouri.",
    phone: "573-634-7727",
    website: "https://namimo.org/",
    services: ["family-support", "education", "advocacy"],
    languages: ["english"],
    populations: ["family", "general"],
    medicaid: null,
    slidingScale: true,
    hours: "Business hours",
    region: "Statewide",
  },
  {
    id: "chads",
    name: "CHADS Coalition for Mental Health",
    short: "Youth mental health — suicide prevention and education.",
    description: "Evidence-based suicide-prevention and mental-health education in schools across the St. Louis region. Family services for grieving families, youth counseling, peer-led support.",
    phone: "314-952-8274",
    website: "https://www.chadscoalition.org/",
    services: ["therapy", "education", "peer-support"],
    languages: ["english"],
    populations: ["youth", "family"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis metro",
  },
  {
    id: "places",
    name: "Places for People",
    short: "Case management and supportive housing for serious mental illness.",
    description: "Behavioral health, substance use, housing, and employment supports for people living with serious mental illness. Operates in St. Louis City and County.",
    phone: "314-535-5600",
    website: "https://placesforpeople.org/",
    services: ["case-management", "housing", "therapy", "psychiatry"],
    languages: ["english"],
    populations: ["general"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis metro",
  },
  {
    id: "bjcbh",
    name: "BJC Behavioral Health",
    short: "Outpatient mental health and substance-use care.",
    description: "One of the largest community mental-health providers in eastern Missouri. Intake, therapy, psychiatric care, and community-based services.",
    phone: "314-747-7555",
    website: "https://www.bjcbehavioralhealth.org/",
    services: ["therapy", "psychiatry", "case-management", "substance-use"],
    languages: ["english", "spanish"],
    populations: ["general"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "Eastern Missouri",
  },
  {
    id: "ssmbh",
    name: "SSM Health Saint Louis Behavioral Medicine",
    short: "Hospital-based psychiatric and behavioral care.",
    description: "Inpatient, outpatient, and intensive outpatient programs across the St. Louis region. Also psychiatric consultation for primary-care patients within the SSM network.",
    phone: "314-577-8000",
    website: "https://www.ssmhealth.com/",
    services: ["therapy", "psychiatry", "inpatient"],
    languages: ["english"],
    populations: ["general"],
    medicaid: true,
    slidingScale: false,
    hours: "24/7 inpatient; outpatient hours vary",
    region: "St. Louis metro",
  },
  {
    id: "compass",
    name: "Compass Health Network",
    short: "Community mental health across Missouri.",
    description: "Behavioral health, substance use, primary care, and community-based services in over 60 counties. Certified Community Behavioral Health Clinic (CCBHC) model.",
    phone: "844-853-8937",
    website: "https://compasshealthnetwork.org/",
    services: ["therapy", "psychiatry", "case-management", "substance-use", "primary-care"],
    languages: ["english", "spanish"],
    populations: ["general"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "Statewide",
  },
  {
    id: "jfs",
    name: "Jewish Family Services of St. Louis",
    short: "Therapy, case management, and caregiver support — open to everyone.",
    description: "Counseling, psychiatry, older-adult services, and caregiver support. Serves Jewish and non-Jewish clients alike; operates on a sliding scale.",
    phone: "314-993-1000",
    website: "https://jfsstl.org/",
    services: ["therapy", "psychiatry", "case-management", "family-support"],
    languages: ["english"],
    populations: ["family", "older-adults", "general"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis metro",
  },
  {
    id: "ccstl",
    name: "Catholic Charities of St. Louis",
    short: "Case management, family services, and mental-health support.",
    description: "Counseling, legal services for immigrants, domestic violence services, homelessness prevention, and coordination with St. Louis-area affiliates. Serves people of all faiths.",
    phone: "314-367-5500",
    website: "https://ccstl.org/",
    services: ["therapy", "case-management", "family-support", "legal", "housing"],
    languages: ["english", "spanish"],
    populations: ["family", "immigrants", "general"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis metro",
  },
  {
    id: "casa",
    name: "Casa de Salud",
    short: "Primary and behavioral health for uninsured and Spanish-speaking patients.",
    description: "Low-cost medical home for uninsured adults, with a focus on immigrant and refugee communities. Integrated behavioral health and specialty-care navigation.",
    phone: "314-977-1250",
    website: "https://casadesaludstl.org/",
    services: ["therapy", "primary-care"],
    languages: ["english", "spanish"],
    populations: ["immigrants", "uninsured"],
    medicaid: false,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis City",
  },
  {
    id: "iistl",
    name: "International Institute of St. Louis",
    short: "Mental-health and resettlement support for refugees and immigrants.",
    description: "Case management, counseling, and interpretation services for refugees, asylum-seekers, and immigrants across many languages — including Bosnian, Arabic, Dari, Pashto, Spanish, Swahili, and Vietnamese.",
    phone: "314-773-9090",
    website: "https://iistl.org/",
    services: ["therapy", "case-management", "family-support", "legal"],
    languages: ["english", "bosnian", "spanish", "arabic"],
    populations: ["immigrants", "family"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis metro",
  },
  {
    id: "umsl",
    name: "UMSL Community Psychological Service",
    short: "Sliding-scale therapy delivered by doctoral trainees.",
    description: "Training clinic at the University of Missouri-St. Louis. Individual, couples, and family therapy on a sliding scale; psychological assessment.",
    phone: "314-516-5824",
    website: "https://www.umsl.edu/~psychology/community-psychological-service.html",
    services: ["therapy", "assessment"],
    languages: ["english"],
    populations: ["general", "family", "uninsured"],
    medicaid: false,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis City",
  },
  {
    id: "pfh",
    name: "Preferred Family Healthcare",
    short: "Integrated substance-use and mental-health services.",
    description: "Statewide provider with programs for co-occurring mental-health and substance-use conditions, plus youth and family services (including the former Great Circle programs).",
    phone: "888-222-8799",
    website: "https://www.pfh.org/",
    services: ["therapy", "psychiatry", "substance-use", "case-management"],
    languages: ["english"],
    populations: ["general", "youth", "family"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "Statewide",
  },
  {
    id: "mocit",
    name: "Missouri CIT Council",
    short: "Crisis Intervention Team training and coordination for law enforcement.",
    description: "Statewide council that coordinates Crisis Intervention Team (CIT) training for Missouri law enforcement. Useful if you're advocating for CIT in your department or reporting concerns.",
    phone: "",
    website: "https://mocitcouncil.org/",
    services: ["advocacy", "education"],
    languages: ["english"],
    populations: ["general"],
    medicaid: null,
    slidingScale: true,
    hours: "Business hours",
    region: "Statewide",
  },
  {
    id: "lsem",
    name: "Legal Services of Eastern Missouri",
    short: "Free civil legal help for low-income Missourians.",
    description: "Housing, benefits, family law, and civil rights representation — including help with SSI/SSDI denials, guardianship questions, and tenant protection.",
    phone: "314-534-4200",
    website: "https://lsem.org/",
    services: ["legal"],
    languages: ["english", "spanish"],
    populations: ["general", "uninsured"],
    medicaid: null,
    slidingScale: true,
    hours: "Business hours",
    region: "Eastern Missouri",
  },
  {
    id: "mopas",
    name: "Missouri Protection & Advocacy Services",
    short: "Free legal advocacy for people with disabilities.",
    description: "Federally-mandated protection and advocacy agency. Helps with civil-rights issues in hospitals, schools, institutions, and the community — including involuntary commitment questions.",
    phone: "573-893-3333",
    website: "https://www.moadvocacy.org/",
    services: ["legal", "advocacy"],
    languages: ["english"],
    populations: ["general"],
    medicaid: null,
    slidingScale: true,
    hours: "Business hours",
    region: "Statewide",
  },
  {
    id: "stpat",
    name: "St. Patrick Center",
    short: "Housing and behavioral health for people experiencing homelessness.",
    description: "Housing-first supportive services, behavioral-health care, employment services, and veterans' programs across St. Louis.",
    phone: "314-802-0700",
    website: "https://www.stpatrickcenter.org/",
    services: ["housing", "case-management", "therapy", "substance-use"],
    languages: ["english"],
    populations: ["unhoused", "veterans", "general"],
    medicaid: true,
    slidingScale: true,
    hours: "Business hours",
    region: "St. Louis City",
  },
  {
    id: "empowermo",
    name: "Empower Missouri",
    short: "Statewide advocacy coalition — economic justice + mental health.",
    description: "Policy coalition covering housing, Medicaid, hunger, and criminal-justice reform. Useful for advocacy — they coordinate legislative action-alerts and testimony campaigns.",
    phone: "573-634-2901",
    website: "https://www.empowermissouri.org/",
    services: ["advocacy"],
    languages: ["english"],
    populations: ["general"],
    medicaid: null,
    slidingScale: true,
    hours: "Business hours",
    region: "Statewide",
  },
];
