const PROGRAMS_DATA = [
  {
    id: "peer-to-peer",
    name: "NAMI Peer-to-Peer",
    category: "Education",
    icon: "people",
    color: "teal",
    summary: "Free 8-session educational program for adults with mental health conditions.",
    description:
      "Led by trained mentors living in recovery, this program teaches practical strategies for managing symptoms, building resilience, and setting personal goals. Covers wellness planning, communication skills, and relapse prevention.",
    audience: "Adults living with a mental health condition",
    format: "8 weekly sessions, 2 hours each",
    cost: "Free",
    registration: "Pre-registration required",
    contact: "namistl.org",
    tags: ["education", "peer support", "recovery"],
  },
  {
    id: "family-to-family",
    name: "NAMI Family-to-Family",
    category: "Education",
    icon: "family",
    color: "blue",
    summary: "Free 8-session course for families, partners, and friends of people with mental illness.",
    description:
      "Teaches families about diagnoses, treatment, communication strategies, self-care, crisis preparation, and advocacy. Led by trained family members who have lived experience as caregivers.",
    audience: "Family members, caregivers, and loved ones",
    format: "8 weekly sessions, 2.5 hours each",
    cost: "Free",
    registration: "Pre-registration required",
    contact: "namistl.org",
    tags: ["family", "education", "caregivers"],
  },
  {
    id: "support-groups",
    name: "NAMI Support Groups",
    category: "Support",
    icon: "circle",
    color: "purple",
    summary: "Free peer-led support groups for individuals and families affected by mental illness.",
    description:
      "Ongoing groups providing a safe, confidential space to share experiences, learn coping strategies, and find mutual support. Includes NAMI Connection (for individuals) and NAMI Family Support Group (for families).",
    audience: "Individuals living with mental illness and their families",
    format: "Ongoing, typically weekly or biweekly, 90 minutes",
    cost: "Free",
    registration: "Drop-in welcome; no pre-registration needed",
    contact: "namistl.org",
    tags: ["support", "peer", "ongoing"],
  },
  {
    id: "ending-the-silence",
    name: "NAMI Ending the Silence",
    category: "Youth & Schools",
    icon: "school",
    color: "coral",
    summary: "Mental health awareness presentation for middle and high school students.",
    description:
      "A 50-minute presentation that helps young people understand mental health conditions, recognize warning signs, and know how to get help. Includes a personal story from a young adult living with a mental health condition.",
    audience: "Middle and high school students, school staff",
    format: "50-minute in-school presentation",
    cost: "Free",
    registration: "Schools schedule through NAMI STL",
    contact: "namistl.org",
    tags: ["youth", "schools", "awareness", "prevention"],
  },
  {
    id: "provider-education",
    name: "NAMI Provider Education",
    category: "Professional",
    icon: "medical",
    color: "green",
    summary: "Training for mental health professionals, first responders, and faith communities.",
    description:
      "Builds understanding among providers and community professionals about the experience of living with mental illness — from the perspective of individuals and families. Includes modules for law enforcement (CIT), healthcare, and faith-based settings.",
    audience: "Healthcare providers, law enforcement, clergy, educators",
    format: "Varies — 2-hour to full-day sessions",
    cost: "Free or low-cost depending on format",
    registration: "Contact NAMI STL to schedule",
    contact: "namistl.org",
    tags: ["professional", "CIT", "training", "providers"],
  },
  {
    id: "helpline",
    name: "NAMI HelpLine",
    category: "Crisis & Navigation",
    icon: "phone",
    color: "red",
    summary: "Free information, referrals, and support for individuals and families.",
    description:
      "Trained volunteers and staff provide information about mental health conditions, treatment options, support programs, and local resources. Available Monday through Friday. For crisis support, call or text 988.",
    audience: "Anyone seeking mental health information or support",
    format: "Phone, email, and online chat",
    cost: "Free",
    registration: "No registration needed",
    contact: "1-800-950-NAMI (6264) or info@nami.org",
    tags: ["helpline", "crisis", "referral", "navigation"],
  },
  {
    id: "smarts",
    name: "NAMI Smarts for Advocacy",
    category: "Advocacy",
    icon: "megaphone",
    color: "amber",
    summary: "Training program that teaches advocacy skills for mental health policy change.",
    description:
      "Hands-on workshop that teaches participants how to communicate with policymakers, share personal stories effectively, understand the legislative process, and advocate for mental health funding and services at the local, state, and federal level.",
    audience: "Anyone interested in mental health advocacy",
    format: "Half-day workshop or multi-session series",
    cost: "Free",
    registration: "Pre-registration required",
    contact: "namistl.org",
    tags: ["advocacy", "policy", "legislature", "training"],
  },
  {
    id: "nami-walks",
    name: "NAMIWalks St. Louis",
    category: "Fundraising & Awareness",
    icon: "walk",
    color: "teal",
    summary: "Annual community walk to raise awareness and funds for mental health.",
    description:
      "The largest mental health awareness and fundraising event in the region. Teams and individuals walk together to fight stigma, raise funds for NAMI programs, and show the community that mental health matters.",
    audience: "Everyone — individuals, families, teams, corporate sponsors",
    format: "Annual outdoor walk event, typically spring",
    cost: "Free to register; fundraising encouraged",
    registration: "Register online at namiwalks.org",
    contact: "namistl.org",
    tags: ["fundraising", "walk", "awareness", "community"],
  },
];
